### ISSUE TITLE
Adding Push, Pull, and Remotes- A Roadmap

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab-git#234]
This post is to explore the implementation of the push and pull functionality, as well as the implications that functionality has for remotes. In the interest of keeping this extension as simple as possible, we're looking at implementing 

## Stage 1 - Introduce Push/Pull functionality
- [x]  Add 'Push,' Default (Origin unless otherwise changed)
- [x]  Add 'Pull,' Default (Origin unless otherwise changed)

## Stage 2 - Introduce remotes
- [x] Add 'Pull from,' existing remotes (manage remotes in the command line)

## Stage 3 - Allow pushing to remotes and 
- [x] Add 'Push to,' (Allow users to specify which remote to push to)
- [x] Add UI functionality to add/remove remotes.

**Comment by tgeorgeux** [comment]
@weihwang @jaipreet We're thinking about where to place the Push and Pull buttons. This conversation surfaced the fact that when you checkout another branch, that also defaults to exposing which remote that branch is 'pointed' to. Is it going to be possible to even have the notion of pushing and pulling without the notion of which remote you are pointing to? 

I ask because it seems like if somebody had a repo (with remotes) set up on their hard drive, and they linked the Git extension, it may immediately break.

**Comment by dhirschfeld** [comment]
I'm a bit agnostic to GUI interfaces for operations such as push/pull etc as the terminal's available and is more powerful/flexible.

The value for me in a GUI git interface is knowing exactly what has changed. In this respect the VSCode diff-view is pretty close to perfect IMHO. All files which have changed are listed and clicking on any of them brings up a great diff view which you can edit. From the listing you can choose what to stage, including highlighting particular lines from a file and only staging them.

Sorry, this is a bit OT for this issue. I guess my point is there are higher value-add improvements than putting a huge effort into what can already be accomplished in the terminal. Some effort and basic functionality sure - that would also be useful for my git-inexperienced users.

**Comment by tgeorgeux** [comment]
@jaipreet-s If you want to weigh in on what your priority will be in this issue I'll update the checklist for easy reference.

**Comment by jaipreet-s** [comment]
I think one thing that I'd like to be listed out in all the stages is what branch we'll be pushing/pulling from

**Comment by weihwang** [comment]
https://www.figma.com/file/UyNpeQNuTj6Uv74MoEJDh3ji/Git-extension?node-id=507%3A1156

I have few proposals in the mockup above I'd like to get feedback on.

Issues I am trying to address:

* Surface both current and target repository of push/pull actions
* A settings gear icon to add remotes if needed and change targets.
* simplify access to history as another section called "commits" that avoids the need to toggle across history, and a smoother transition to "view more" history in the terminal.
* Testing a top-down organization that moves changes through staging to commit to history.
* A fly-out proposal for viewing more details of the commits if needed, or to have the action to view diff of the commit.

**Comment by weihwang** [comment]
Proposal for visibility of target branches, in preparation for push/pull actions: https://www.figma.com/file/UyNpeQNuTj6Uv74MoEJDh3ji/Git-extension?node-id=524%3A3110

**Comment by weihwang** [comment]
Proposal for tabbed history view, which is related to how we may think about push/pull actions:
https://www.figma.com/file/UyNpeQNuTj6Uv74MoEJDh3ji/Git-extension?node-id=517%3A1718

**Comment by ellisonbg** [comment]
Can we add the points here to the roadmap?

**Comment by weihwang** [comment]
@ellisonbg thanks for the feedback. I will move the comment updates above into separate issues.

**Comment by weihwang** [comment]
The issues handle individual features, which may or may not be dependent on each other. I try to call it out when it's relevant. I think we still need a larger story tracked somewhere.

**Comment by jaipreet-s** [comment]
I'm tagging this to the 0.5 milestone. We'll likely break this down to remove the stuff immediately out of scope.

**Comment by fcollonval** [comment]
Solved by https://github.com/jupyterlab/jupyterlab-git/pull/1146
