### ISSUE TITLE
Add push/pull actions

### ISSUE THREAD

**Issue by weihwang** [jupyterlab/jupyterlab-git#246]
Proposals to add push/pull actions to the plugin.
https://www.figma.com/file/UyNpeQNuTj6Uv74MoEJDh3ji/Git-extension?node-id=507%3A1156

**Pre-requisite**
#244 - Surface target branch to inform users before they make a pull/push action.

**Option 1**
Push/pull actions embedded in a history tab #245 (more overview info for history) to provide context to these actions.
![image](https://user-images.githubusercontent.com/551333/46972017-625e5a80-d072-11e8-88e8-5bdc4190be48.png)

**Option 2**
Push/pull actions at a high level (icons TBD) to allow push pull with history view, or working environment view.
![image](https://user-images.githubusercontent.com/551333/46972203-ddc00c00-d072-11e8-9ee5-5ce25b98ed16.png)

### TASK BREAKDOWN
- [X]  Backend for Pull
- [X]  Backend for Push
- []  Frontend for Pull
- []  Frontend for Push

**Comment by jaipreet-s** [comment]
@weihwang 

1.  Is there an issue for moving the *up* and *trash* icons to the right of the main panel?
2. What is the state of the push/pull actions when there is a merge conflict?
3. What is the state of th push/pull actions when there is no upstream defined?

**Comment by weihwang** [comment]
@jaipreet-s 

1. #227 is the issue for commit change list styling.
2. Do you know if merge conflicts we can show in the extension? If so, push/pull can be disabled as long as we have a persistent notification of why push/pull is disabled.
3. If we're not supporting creating remote branch/tracking, I think we may need to disable. Otherwise, on pull/push we need to show the terminal for more actions to take.

**Comment by weihwang** [comment]
Agree on #2.

**Comment by jaipreet-s** [comment]
Regarding #2, I would making the push/pull button visible, but disabled, and adding a tooltip to show why they are disabled. There should also be a way to switch to the terminal quickly to see the actual merge conflicts

Regarding #3, @weihwang do we have any mockups which show the state of the push/pull UX in that scenario?

Thanks!

**Comment by tgeorgeux** [comment]
The final frame of this is showing a fly-out window for details. Do we also have an option that would expand in the sidebar? We don't currently have any fly-out interactions with out sidebars at this point in JupyterLab.

**Comment by weihwang** [comment]
@tgeorgeux added an inline option. Is there any styling for links, or guidance for icon based actions vs. text?

**Comment by brylie** [comment]
I like the high-level push/pull buttons. This would be similar to an IDE, showing frequently used Git commands. E.g. Atom Git integration:
![screenshot_20181114_124309](https://user-images.githubusercontent.com/17307/48477672-db380a00-e80a-11e8-8116-b60de6b10461.png)

**Comment by jaipreet-s** [comment]
- [ ]  Backend for Pull
- [ ]  Backend for Push
- [ ]  Frontend for Pull
- [ ]  Frontend for Push

**Comment by jaipreet-s** [comment]
Released in 0.5
