### ISSUE TITLE
Final checklist for 0.10.0 release

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab-git#568]
5 smallish PRs left in the [milestone](https://github.com/jupyterlab/jupyterlab-git/milestone/13)
  
- [x] #476 update readme
  - The animated gifs need to be updated, ideally right after #571 gets pulled in
- [x] #548 non-ascii support
- [x] #556 fix hard freeze on failed clone
- [x] #561 fix the "add-group" buttons
- [x] #571 fix styling issues with FileList and FileItem
  - Someone (not me, since I wrote it) needs to review this PR

**Comment by mlucool** [comment]
Can these two be included in the 0.10 release please?
https://github.com/jupyterlab/jupyterlab-git/pull/564
https://github.com/jupyterlab/jupyterlab-git/pull/536

**Comment by telamonian** [comment]
I'd prefer not to block on either of these. 0.10.0 has waited long enough. That being said, if stuff gets done quickly I'm open to reconsidering:

- #536 still needs a redesign/rethink, since the text box it modifies was removed in #509
- #564 still needs at least a good test. I think there might also be some potential UI concerns (I added a related comment to that thread)

**Comment by kgryte** [comment]
@telamonian I should have #536 updated by tomorrow's end (Friday, 3/20). Having to refactor most of the UI changes, but should be straightforward to review. I'd like to see #536 merged in, as well, for `0.10.0`, as the messaging and UX for reverting and resetting needs attention (as demonstrated in the original PR).

**Comment by kgryte** [comment]
@telamonian #536 has been redesigned and rethought to address the changes in `master`. Its main emphasis in is improving the UX of performing resetting/reverting, including visual presentation. Should be ready for review.

**Comment by telamonian** [comment]
I got #536 in. I think that #564 still needs some more thought. All that's left is #571 (needs a review), then finally the README update in #476, and then I think 0.10.0 will be ready for release!

I'm hoping to do the release tomorrow

**Comment by telamonian** [comment]
Allllmost done, all that's left is the update to the README in #476

**Comment by telamonian** [comment]
All of the 0.10.0 PRs have been merged, now on to the release!

**Comment by telamonian** [comment]
It's done! `jupyterlab-git` 0.10.0 is officially released:

https://pypi.org/project/jupyterlab-git/0.10.0/
https://www.npmjs.com/package/@jupyterlab/git/v/0.10.0
